### ISSUE TITLE
Waiting GRI

### ISSUE THREAD

**Issue by zeno0207** [GenZmeY/KF2-CustomTraderInventory#4]
What does Waiting GRI mean?It always happends after sync finished.I maybe wait for several minutes,otherwise I cant join the game.

**Comment by GenZmeY** [comment]
> What does Waiting GRI mean?It always happends after sync finished.I maybe wait for several minutes,otherwise I cant join the game.

GRI is GameReplicationInfo, an object through which game data is replicated to the client (among other things, trader's inventory [which is what we need](https://github.com/GenZmeY/KF2-CustomTraderInventory/blob/master/CTI/Classes/CTI_RepInfo.uc#L236)). If CTI replicated its data before GRI created on client, then we have to wait to update the inventory.

If your wait doesn't end, the GRI is apparently not being created for some reason. Need to understand why. I don't know your configuration so I can't say for sure, but I'm guessing it might be due to a mod conflict.

I would recommend running the server with CTI only, and then adding mods one by one to see where the problem occurs
